#pragma once
#include "ClientPacketHandler.h"

unordered_map<uint16, string> packetIdToString =
{
	{PKT_S_SERVER_CHAT, "PKT_S_SERVER_CHAT"},
	{PKT_S_CREATE_ROOM, "PKT_S_CREATE_ROOM"},

	{PKT_C_TEST, "PKT_C_TEST"},
	{PKT_S_TEST, "PKT_S_TEST"},

	{PKT_C_SIGNUP, "PKT_C_SIGNUP"},
	{PKT_S_SIGNUP, "PKT_S_SIGNUP"},

	{PKT_C_LOGIN, "PKT_C_LOGIN"},
	{PKT_S_LOGIN, "PKT_S_LOGIN"},

	{PKT_C_ENTER_GAME, "PKT_C_ENTER_GAME"},
	{PKT_S_ENTER_GAME, "PKT_S_ENTER_GAME"},

	{PKT_C_CHAT, "PKT_C_CHAT"},
	{PKT_S_CHAT, "PKT_S_CHAT"},

	{PKT_C_MOVE, "PKT_C_MOVE"},
	{PKT_S_MOVE, "PKT_S_MOVE"},

	{PKT_C_SHOT, "PKT_C_SHOT"},
	{PKT_S_SHOT, "PKT_S_SHOT"},

	{PKT_C_HIT, "PKT_C_HIT"},
	{PKT_S_HIT, "PKT_S_HIT"},

	{PKT_C_EAT_ROOM_ITEM, "PKT_C_EAT_ROOM_ITEM"},
	{PKT_S_EAT_ROOM_ITEM, "PKT_S_EAT_ROOM_ITEM"},

	{PKT_C_USE_ITEM, "PKT_C_USE_ITEM"},
	{PKT_S_USE_ITEM, "PKT_S_USE_ITEM"},

	{PKT_C_CREATE_PARTY, "PKT_C_CREATE_PARTY"},
	{PKT_S_CREATE_PARTY, "PKT_S_CREATE_PARTY"},

	{PKT_C_JOIN_PARTY, "PKT_C_JOIN_PARTY"},
	{PKT_S_JOIN_PARTY, "PKT_S_JOIN_PARTY"},

	{PKT_C_WITHDRAW_PARTY, "PKT_C_WITHDRAW_PARTY"},
	{PKT_S_WITHDRAW_PARTY, "PKT_S_WITHDRAW_PARTY"},
	
	{PKT_C_MY_PARTY, "PKT_C_MY_PARTY"},
	{PKT_S_MY_PARTY, "PKT_S_MY_PARTY"},
	
	{PKT_C_ALL_PARTY, "PKT_C_ALL_PARTY"},
	{PKT_S_ALL_PARTY, "PKT_S_ALL_PARTY"},
};

class PacketUtils
{
};

